version: 2.1
executors:
  docker-publisher:
    environment:
        IMAGE_NAME: mukuntharya2022/gosimple
        DOCKERHUB_PASS: $dockerpass
        DOCKERHUB_USER: $dockeruser
    docker:
      - image: circleci/buildpack-deps:stretch
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - working_directory: /home/mukunth/circleci
      - setup_remote_docker:
         docker_layer_caching: false
      - run: go test
      - run:
          name: archive the image
          command: docker build -t $IMAGE_NAME:v2 .
      - run:
          name: archive the image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
         root: .
         paths:
           - ./image.tar
  publish-latest:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: publish image to docker hub
          command: | 
            docker push $IMAGE_NAME:v2
      
workflows:
  version: 2
  build_master:
    jobs:
      - build:
          filter:
             branches:
               only: master
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master